
package com.gzgb.epo.crawlerClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IMyService", targetNamespace = "http://service.gzgb.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMyService {


    /**
     * 
     * @param webGatherNodeBean
     * @param enable
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(name = "crawlerResult", targetNamespace = "")
    @RequestWrapper(localName = "crawlerOperation", targetNamespace = "http://service.gzgb.org/", className = "com.gzgb.epo.crawlerClient.CrawlerOperation")
    @ResponseWrapper(localName = "crawlerOperationResponse", targetNamespace = "http://service.gzgb.org/", className = "com.gzgb.epo.crawlerClient.CrawlerOperationResponse")
    public int crawlerOperation(
        @WebParam(name = "enable", targetNamespace = "")
        int enable,
        @WebParam(name = "webGatherNodeBean", targetNamespace = "")
        WebGatherNodeBean webGatherNodeBean);

}
